from __future__ import annotations

from syntrive.adapters.epub.merged_toc_writer import (
    MergedTocEntry,
    MergedTocMeta,
    MergedTocReader,
    MergedTocWriter,
)


def _entry(chapter_id: str, title: str, heading_level: int = 2, excluded: bool = False) -> MergedTocEntry:
    return MergedTocEntry(
        chapter_id=chapter_id,
        title=title,
        source_files=[f"{chapter_id}.html"],
        excluded=excluded,
        is_discard=False,
        heading_level=heading_level,
    )


class TestWriteH1AndHeadingLevels:
    def test_h1_uses_book_title(self, tmp_path):
        out = tmp_path / "0_toc.md"
        MergedTocWriter().write(
            [_entry("ch_0001", "Chapter 1")],
            MergedTocMeta(book_title="思考,快与慢"),
            out,
        )
        first_line = out.read_text(encoding="utf-8").splitlines()[0]
        assert first_line == "# 思考,快与慢"

    def test_h1_falls_back_to_toc_when_no_book_title(self, tmp_path):
        out = tmp_path / "0_toc.md"
        MergedTocWriter().write([_entry("ch_0001", "Chapter 1")], MergedTocMeta(), out)
        first_line = out.read_text(encoding="utf-8").splitlines()[0]
        assert first_line == "# TOC"

    def test_entries_written_at_their_own_heading_level(self, tmp_path):
        out = tmp_path / "0_toc.md"
        entries = [
            _entry("ch_0001", "Book One", heading_level=2, excluded=True),
            _entry("ch_0002", "Part One", heading_level=3, excluded=True),
            _entry("ch_0003", "Chapter 1", heading_level=4),
        ]
        MergedTocWriter().write(entries, MergedTocMeta(book_title="LOTR"), out)
        lines = out.read_text(encoding="utf-8").splitlines()
        heading_lines = [ln for ln in lines if ln.startswith("#") and "[" in ln]
        assert heading_lines == [
            "## [Book One](ch_0001.html)",
            "### [Part One](ch_0002.html)",
            "#### [Chapter 1](ch_0003.html)",
        ]

    def test_heading_level_clamped_to_h6(self, tmp_path):
        out = tmp_path / "0_toc.md"
        MergedTocWriter().write(
            [_entry("ch_0001", "Deep", heading_level=9)], MergedTocMeta(), out
        )
        lines = out.read_text(encoding="utf-8").splitlines()
        heading_line = next(ln for ln in lines if "[Deep]" in ln)
        assert heading_line.startswith("###### [Deep]")


class TestReadRoundTrip:
    def test_round_trip_preserves_book_title_and_heading_levels(self, tmp_path):
        out = tmp_path / "0_toc.md"
        entries = [
            _entry("ch_0001", "Book One", heading_level=2, excluded=True),
            _entry("ch_0002", "Part One", heading_level=3, excluded=True),
            _entry("ch_0003", "Chapter 1", heading_level=4),
        ]
        MergedTocWriter().write(entries, MergedTocMeta(book_title="LOTR"), out)

        meta, parsed = MergedTocReader().read(out)
        assert meta.book_title == "LOTR"
        by_id = {e.chapter_id: e for e in parsed}
        assert by_id["ch_0001"].heading_level == 2
        assert by_id["ch_0002"].heading_level == 3
        assert by_id["ch_0003"].heading_level == 4
        assert by_id["ch_0001"].excluded is True
        assert by_id["ch_0003"].excluded is False

    def test_backward_compat_old_flat_h2_file_still_parses(self, tmp_path):
        out = tmp_path / "0_toc.md"
        out.write_text(
            "# TOC\n\n"
            "<!-- Auto-generated by SyntriveTTS — safe to edit for review -->\n\n"
            "## [Chapter 1](ch_0001.html)\n"
            "  - sequence_number: 0001\n"
            "  - chapter_name: Chapter 1\n"
            "  - chapter_number: 0001\n"
            "  - volume_name: \n"
            "  - volume_number: \n"
            "  - source_files: ch_0001.html\n"
            "  - excluded: n\n",
            encoding="utf-8",
        )
        meta, parsed = MergedTocReader().read(out)
        assert meta.book_title == ""
        assert len(parsed) == 1
        assert parsed[0].heading_level == 2
        assert parsed[0].chapter_id == "ch_0001"


class TestAuditTable:
    def test_audit_table_appended_after_regular_chapters(self, tmp_path):
        (tmp_path / "ch_0001.html").write_text(
            "<html><body><p>你好世界</p></body></html>", encoding="utf-8"
        )
        out = tmp_path / "0_toc.md"
        MergedTocWriter().write([_entry("ch_0001", "Chapter 1")], MergedTocMeta(), out)
        text = out.read_text(encoding="utf-8")

        assert "## File Size & Character Count (audit)" in text
        size = (tmp_path / "ch_0001.html").stat().st_size
        assert f"| [Chapter 1](ch_0001.html) | ch_0001.html | {size} | 4 |" in text

    def test_reader_ignores_audit_section_no_spurious_entries_or_warnings(
        self, tmp_path, caplog
    ):
        import logging

        (tmp_path / "ch_0001.html").write_text(
            "<html><body><p>x</p></body></html>", encoding="utf-8"
        )
        entries = [_entry("ch_0001", "Chapter 1")]
        out = tmp_path / "0_toc.md"
        MergedTocWriter().write(entries, MergedTocMeta(), out)

        with caplog.at_level(logging.WARNING):
            meta, parsed = MergedTocReader().read(out)

        assert len(parsed) == 1
        assert parsed[0].chapter_id == "ch_0001"
        assert "cannot parse orphan" not in caplog.text

    def test_reader_stops_at_audit_section_even_with_real_discards(self, tmp_path):
        entries = [
            _entry("ch_0001", "Chapter 1"),
            MergedTocEntry(
                chapter_id="ch_9000", title="", source_files=["cover.html"],
                excluded=False, is_discard=True,
            ),
        ]
        (tmp_path / "ch_0001.html").write_text(
            "<html><body><p>x</p></body></html>", encoding="utf-8"
        )
        out = tmp_path / "0_toc.md"
        MergedTocWriter().write(entries, MergedTocMeta(), out)

        meta, parsed = MergedTocReader().read(out)
        by_id = {e.chapter_id: e for e in parsed}
        assert set(by_id) == {"ch_0001", "ch_9000"}
        assert by_id["ch_9000"].is_discard is True
