from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from syntrive.adapters.toc_audit import AUDIT_SECTION_HEADING

logger = logging.getLogger(__name__)

_DEFAULT_EXCLUDED = "n"

_CHAPTER_ID_RE = re.compile(r"^ch_\d{4}$")

_CHAPTER_HEADING_RE = re.compile(r"^(#{2,6}) \[(.+?)\]\((ch_\d{4})\.html\)$")


@dataclass
class MergedTocEntry:
    chapter_id: str
    title: str
    source_files: list[str]
    excluded: bool
    is_discard: bool
    volume_name: str = ""
    volume_number: str = ""
    heading_level: int = 2
    chapter_number: Optional[str] = None
    applied_rules: list[str] = field(default_factory=list)
    sequence_number: str = ""

    sequence_reset: bool = False
    chapter_reset: bool = False
    chapter_clear: bool = False


@dataclass
class MergedTocMeta:
    book_title: str = ""
    merge_mode: str = "flat"


class MergedTocWriter:
    def write(
        self,
        entries: list[MergedTocEntry],
        meta: MergedTocMeta,
        output_path: Path,
    ) -> None:
        h1_title = meta.book_title.strip() if meta.book_title else "TOC"
        lines: list[str] = [
            f"# {h1_title}",
            "",
            "<!-- Auto-generated by SyntriveTTS — safe to edit for review -->",
            f"<!-- merge_mode: {meta.merge_mode} -->",
            "",
        ]

        regular = [e for e in entries if not e.is_discard]
        discards = [e for e in entries if e.is_discard]

        for entry in regular:
            natural_num = entry.chapter_id.split("_", 1)[1]
            num = entry.sequence_number if entry.sequence_number else natural_num
            chapter_num = entry.chapter_number if entry.chapter_number is not None else num
            safe_title = entry.title.replace("[", "\\[").replace("]", "\\]")
            heading_marker = "#" * max(2, min(entry.heading_level, 6))
            lines.append(f"{heading_marker} [{safe_title}]({entry.chapter_id}.html)")
            lines.append(f"  - sequence_number: {num}")
            lines.append(f"  - chapter_name: {entry.title}")
            lines.append(f"  - chapter_number: {chapter_num}")
            lines.append(f"  - volume_name: {entry.volume_name}")
            lines.append(f"  - volume_number: {entry.volume_number}")
            src = ", ".join(entry.source_files)
            lines.append(f"  - source_files: {src}")
            excl = "y" if entry.excluded else "n"
            lines.append(f"  - excluded: {excl}")
            if entry.applied_rules:
                rules_str = ", ".join(entry.applied_rules)
                lines.append(f"  - applied_rules: [{rules_str}]")
            if entry.sequence_reset:
                lines.append("  - sequence_reset: y")
            if entry.chapter_reset:
                lines.append("  - chapter_reset: y")
            if entry.chapter_clear:
                lines.append("  - chapter_clear: y")

        if discards:
            lines.extend([
                "",
                "---",
                "",
                "| orphan_files | source_files |",
                "|------------|-------|",
            ])
            for entry in discards:
                ch_link = f"[{entry.chapter_id}.html]({entry.chapter_id}.html)"
                src_links = ", ".join(f"[{s}](../raw/{s})" for s in entry.source_files)
                lines.append(f"| {ch_link} | {src_links} |")

        if regular:
            from syntrive.adapters.toc_audit import build_audit_table_lines

            audit_rows = [
                (entry.title, f"{entry.chapter_id}.html",
                 output_path.parent / f"{entry.chapter_id}.html")
                for entry in regular
            ]
            lines.extend(build_audit_table_lines(audit_rows, strip_html=True))

        lines.append("")
        output_path.write_text("\n".join(lines), encoding="utf-8")

        logger.info(
            "MergedTocWriter: wrote %s — %d chapters, %d discard (ch_9NNN)",
            output_path.name, len(regular), len(discards),
        )


class MergedTocReader:
    def read(self, toc_path: Path) -> tuple[MergedTocMeta, list[MergedTocEntry]]:
        if not toc_path.exists():
            logger.warning("MergedTocReader: file not found: %s", toc_path)
            return MergedTocMeta(), []

        try:
            raw = toc_path.read_text(encoding="utf-8")
        except Exception as exc:
            logger.error("MergedTocReader: cannot read %s: %s", toc_path, exc)
            return MergedTocMeta(), []

        lines = raw.splitlines()

        first_nonempty = next((ln.strip() for ln in lines if ln.strip()), "")
        if first_nonempty == "---":
            meta, body_start = _parse_frontmatter(lines, toc_path)
            entries = _parse_table(lines, body_start, toc_path)
        else:
            meta = MergedTocMeta(book_title=_parse_h1_title(lines), merge_mode=_parse_merge_mode_comment(lines))
            entries = _parse_new_format(lines, toc_path)

        logger.info(
            "MergedTocReader: parsed %s — %d entries (%d excluded)",
            toc_path.name,
            len(entries),
            sum(1 for e in entries if e.excluded),
        )
        return meta, entries


def _parse_frontmatter(
    lines: list[str],
    path: Path,
) -> tuple[MergedTocMeta, int]:
    import yaml

    meta = MergedTocMeta()
    if not lines or lines[0].strip() != "---":
        return meta, 0

    end_idx: Optional[int] = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end_idx = i
            break

    if end_idx is None:
        logger.warning(
            "MergedTocReader: %s:1: frontmatter '---' opened but no closing '---' found",
            path,
        )
        return meta, 0

    fm_text = "\n".join(lines[1:end_idx])
    try:
        data = yaml.safe_load(fm_text) or {}
        meta.book_title = str(data.get("book_title", "") or "")
        meta.merge_mode = str(data.get("merge_mode", "flat") or "flat")
    except yaml.YAMLError as exc:
        logger.warning(
            "MergedTocReader: %s:1: YAML frontmatter parse error — %s (using defaults)",
            path, exc,
        )

    return meta, end_idx + 1


def _parse_table(
    lines: list[str],
    start: int,
    path: Path,
) -> list[MergedTocEntry]:
    entries: list[MergedTocEntry] = []
    header_seen = False

    for offset, line in enumerate(lines[start:]):
        line_num = start + offset + 1
        stripped = line.strip()

        if not stripped:
            continue
        if stripped.startswith("#") or stripped.startswith("<!--"):
            continue
        if not stripped.startswith("|"):
            continue
        if re.match(r"^\|[\s\-|]+\|$", stripped):
            continue
        if not header_seen:
            header_seen = True
            continue

        entry = _parse_table_row(stripped, line_num, path)
        if entry is not None:
            entries.append(entry)

    return entries


def _parse_table_row(
    line: str,
    line_num: int,
    path: Path,
) -> Optional[MergedTocEntry]:
    cells = [c.strip() for c in line.strip("|").split("|")]
    if len(cells) < 4:
        logger.warning(
            "MergedTocReader: %s:%d: expected 4 columns, got %d — row skipped: %r",
            path, line_num, len(cells), line,
        )
        return None

    chapter_id = cells[0].strip()
    if not chapter_id or not _CHAPTER_ID_RE.match(chapter_id):
        logger.warning(
            "MergedTocReader: %s:%d: invalid chapter_id=%r (expected ch_DDDD) — skipped",
            path, line_num, chapter_id,
        )
        return None

    title = cells[1].strip().replace("\\|", "|")

    source_files = [s.strip() for s in cells[2].split(",") if s.strip()]

    excl_raw = cells[3].strip().lower()
    if excl_raw not in ("y", "n"):
        logger.warning(
            "MergedTocReader: %s:%d: invalid excluded=%r (expected 'y' or 'n') "
            "— defaulting to 'n'",
            path, line_num, excl_raw,
        )
        excl_raw = _DEFAULT_EXCLUDED

    return MergedTocEntry(
        chapter_id=chapter_id,
        title=title,
        source_files=source_files,
        excluded=(excl_raw == "y"),
        is_discard=_is_discard_id(chapter_id),
    )


def _is_discard_id(chapter_id: str) -> bool:
    try:
        num = int(chapter_id.split("_", 1)[1])
        return num >= 9000
    except (IndexError, ValueError):
        return False


def _parse_h1_title(lines: list[str]) -> str:
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("# ") and not stripped.startswith("## "):
            title = stripped[2:].strip()
            return "" if title == "TOC" else title
        break
    return ""


_EXCLUDED_LINE_RE = re.compile(r"^(\s+- excluded:)[ \t]*(\S*)(\s*)$")


def set_excluded_flags(text: str, excluded_ids: frozenset[str]) -> tuple[str, tuple[str, ...]]:
    out: list[str] = []
    changed: list[str] = []
    current: Optional[str] = None
    for line in text.splitlines(keepends=True):
        body = line.rstrip("\r\n")
        heading = _CHAPTER_HEADING_RE.match(body.strip())
        if heading:
            current = heading.group(3)
        elif body.strip() == AUDIT_SECTION_HEADING or body.strip() == "---":
            current = None
        match = _EXCLUDED_LINE_RE.match(body) if current else None
        if match:
            wanted = "y" if current in excluded_ids else "n"
            if match.group(2).lower() != wanted:
                changed.append(current)
                line = f"{match.group(1)} {wanted}{match.group(3)}{line[len(body):]}"
        out.append(line)
    return "".join(out), tuple(changed)


_MERGE_MODE_COMMENT_RE = re.compile(r"^<!--\s*merge_mode:\s*([a-z_]+)\s*-->$")


def _parse_merge_mode_comment(lines: list[str]) -> str:
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            break
        match = _MERGE_MODE_COMMENT_RE.match(stripped)
        if match:
            return match.group(1)
    return ""


def _parse_new_format(
    lines: list[str],
    path: Path,
) -> list[MergedTocEntry]:
    entries: list[MergedTocEntry] = []

    current_id: Optional[str] = None
    current_title: Optional[str] = None
    current_level: int = 2
    current_attrs: dict[str, str] = {}
    in_orphan_section: bool = False
    orphan_header_seen: bool = False

    for line_num, line in enumerate(lines, start=1):
        stripped = line.strip()

        if stripped == AUDIT_SECTION_HEADING:
            break

        if not stripped or stripped.startswith("<!--") or (
            stripped.startswith("# ") and not stripped.startswith("## ")
        ):
            continue

        if stripped == "---" and not in_orphan_section:
            if current_id is not None:
                entries.append(
                    _build_entry_from_attrs(
                        current_id, current_title, current_level, current_attrs, path, line_num
                    )
                )
                current_id = None
                current_title = None
                current_attrs = {}
            in_orphan_section = True
            continue

        if in_orphan_section:
            if not stripped.startswith("|"):
                continue
            if re.match(r"^\|[\s\-|]+\|$", stripped):
                continue
            if not orphan_header_seen:
                orphan_header_seen = True
                continue
            entry = _parse_orphan_row(stripped, line_num, path)
            if entry is not None:
                entries.append(entry)
            continue

        if stripped.startswith("#"):
            if current_id is not None:
                entries.append(
                    _build_entry_from_attrs(
                        current_id, current_title, current_level, current_attrs, path, line_num
                    )
                )
                current_attrs = {}
            m = _CHAPTER_HEADING_RE.match(stripped)
            if m:
                current_level = len(m.group(1))
                current_title = m.group(2).replace("\\[", "[").replace("\\]", "]")
                current_id = m.group(3)
            else:
                logger.warning(
                    "MergedTocReader: %s:%d: unrecognised heading — skipped: %r",
                    path, line_num, stripped,
                )
                current_id = None
                current_title = None
            continue

        if stripped.startswith("- ") and current_id is not None:
            m = re.match(r"^- (\w+):\s*(.*)$", stripped)
            if m:
                current_attrs[m.group(1)] = m.group(2).strip()

    if current_id is not None:
        entries.append(
            _build_entry_from_attrs(
                current_id, current_title, current_level, current_attrs, path, len(lines)
            )
        )

    return entries


def _build_entry_from_attrs(
    chapter_id: str,
    title: Optional[str],
    heading_level: int,
    attrs: dict[str, str],
    path: Path,
    line_num: int,
) -> MergedTocEntry:
    chapter_name = attrs.get("chapter_name", "").strip() or (title or "")
    src_raw = attrs.get("source_files", "")
    source_files = [s.strip() for s in src_raw.split(",") if s.strip()]

    excl_raw = attrs.get("excluded", "n").strip().lower()
    if excl_raw not in ("y", "n"):
        logger.warning(
            "MergedTocReader: %s:%d: invalid excluded=%r for %s — defaulting to 'n'",
            path, line_num, excl_raw, chapter_id,
        )
        excl_raw = _DEFAULT_EXCLUDED

    applied_rules_raw = attrs.get("applied_rules", "").strip().strip("[]")
    applied_rules = [r.strip() for r in applied_rules_raw.split(",") if r.strip()]

    def _flag(key: str) -> bool:
        return attrs.get(key, "").strip().lower() == "y"

    return MergedTocEntry(
        chapter_id=chapter_id,
        title=chapter_name,
        source_files=source_files,
        excluded=(excl_raw == "y"),
        is_discard=False,
        volume_name=attrs.get("volume_name", "").strip(),
        volume_number=attrs.get("volume_number", "").strip(),
        chapter_number=attrs["chapter_number"].strip() if "chapter_number" in attrs else None,
        applied_rules=applied_rules,
        sequence_number=attrs.get("sequence_number", "").strip(),
        sequence_reset=_flag("sequence_reset"),
        chapter_reset=_flag("chapter_reset"),
        chapter_clear=_flag("chapter_clear"),
        heading_level=heading_level,
    )


def apply_toc_reset_flags(entries: list[MergedTocEntry]) -> list[MergedTocEntry]:
    import copy as _copy

    result: list[MergedTocEntry] = []
    seq_counter: Optional[int] = None
    ch_counter: Optional[int] = None

    for entry in entries:
        out = _copy.copy(entry)

        if entry.sequence_reset:
            seq_counter = 1
            out.sequence_number = f"{seq_counter:04d}"
            logger.debug(
                "apply_toc_reset_flags: sequence_reset at %s -> sequence_number=0001",
                entry.chapter_id,
            )
        elif seq_counter is not None:
            seq_counter += 1
            out.sequence_number = f"{seq_counter:04d}"

        if entry.chapter_reset:
            ch_counter = 1
            out.chapter_number = f"{ch_counter:04d}"
            logger.debug(
                "apply_toc_reset_flags: chapter_reset at %s -> chapter_number=0001",
                entry.chapter_id,
            )
        elif entry.chapter_clear:
            if ch_counter is not None:
                ch_counter += 1
            out.chapter_number = ""
            logger.debug(
                "apply_toc_reset_flags: chapter_clear at %s -> chapter_number=''",
                entry.chapter_id,
            )
        elif ch_counter is not None:
            ch_counter += 1
            out.chapter_number = f"{ch_counter:04d}"

        out.sequence_reset = False
        out.chapter_reset = False
        out.chapter_clear = False

        result.append(out)

    logger.debug(
        "apply_toc_reset_flags: processed %d entries "
        "(seq_overriding=%s, ch_overriding=%s)",
        len(result),
        seq_counter is not None,
        ch_counter is not None,
    )
    return result


def _parse_orphan_row(
    line: str,
    line_num: int,
    path: Path,
) -> Optional[MergedTocEntry]:
    cells = [c.strip() for c in line.strip("|").split("|")]
    if len(cells) < 2:
        logger.warning(
            "MergedTocReader: %s:%d: orphan row has %d cell(s) (expected >=2) — skipped",
            path, line_num, len(cells),
        )
        return None

    m = re.match(r"^\[(.+?)\.html\]", cells[0])
    if not m:
        logger.warning(
            "MergedTocReader: %s:%d: cannot parse orphan chapter link from %r — skipped",
            path, line_num, cells[0],
        )
        return None

    chapter_id = m.group(1)
    if not _CHAPTER_ID_RE.match(chapter_id):
        logger.warning(
            "MergedTocReader: %s:%d: invalid chapter_id=%r in orphan row — skipped",
            path, line_num, chapter_id,
        )
        return None

    src_matches = re.findall(r"\[([^\]]+)\]\([^)]*\)", cells[1])
    source_files = [s.strip() for s in src_matches if s.strip()]

    return MergedTocEntry(
        chapter_id=chapter_id,
        title="",
        source_files=source_files,
        excluded=True,
        is_discard=True,
        volume_name="",
        volume_number="",
    )
