from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


class TocMdWriter:
    def write(
        self,
        toc_entries: list[tuple[str, str, int]],
        orphan_hrefs: list[str],
        output_path: Path,
        book_title: str = "",
    ) -> None:
        h1_title = book_title.strip() if book_title else "TOC"
        lines: list[str] = [
            f"# {h1_title}",
            "",
            "<!-- Auto-generated by SyntriveTTS — safe to edit for review -->",
            "",
        ]

        if toc_entries:
            for title, href, heading_level in toc_entries:
                basename = Path(href).name
                safe_title = title.replace("[", "\\[").replace("]", "\\]")
                heading_marker = "#" * max(2, min(heading_level, 6))
                lines.append(f"{heading_marker} [{safe_title}]({basename})")
        else:
            lines.append("<!-- No TOC entries found in this EPUB -->")

        if orphan_hrefs:
            lines.extend([
                "",
                "---",
                "",
                "<!-- Files in spine but NOT in TOC: review below, discard if not needed -->",
                "",
            ])
            for href in orphan_hrefs:
                basename = Path(href).name
                lines.append(f"- [{basename}]({basename})")

        if toc_entries:
            from syntrive.adapters.toc_audit import build_audit_table_lines

            audit_rows = [
                (title, Path(href).name, output_path.parent / Path(href).name)
                for title, href, _heading_level in toc_entries
            ]
            lines.extend(build_audit_table_lines(audit_rows, strip_html=True))

        lines.append("")
        content = "\n".join(lines)
        output_path.write_text(content, encoding="utf-8")
        logger.info(
            "TocMdWriter: wrote %s — %d TOC entries, %d orphan files",
            output_path.name,
            len(toc_entries),
            len(orphan_hrefs),
        )
