from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Optional

from syntrive.adapters.toc_audit import AuditTocMeta, build_audit_table_lines

logger = logging.getLogger(__name__)


class TextTocWriter:
    def write(
        self, entries: list, output_path: Path, *, ext: str = "txt", strip_sml: bool = False,
    ) -> None:
        lines: list[str] = [
            "# TOC",
            "",
            "<!-- Auto-generated by SyntriveTTS — safe to edit for review -->",
            "",
        ]

        audit_rows: list[tuple[str, str, Path]] = []
        audit_toc_meta: list[AuditTocMeta] = []
        for entry in entries:
            if entry.is_discard or entry.excluded:
                continue

            seq_num = entry.sequence_number or entry.chapter_id.split("_", 1)[-1]
            filename = f"ch_{seq_num}.{ext}"
            chapter_num = entry.chapter_number if entry.chapter_number is not None else seq_num

            safe_title = entry.title.replace("[", "\\[").replace("]", "\\]")

            lines.append(f"## [{safe_title}]({filename})")
            lines.append(f"  - sequence_number: {seq_num}")
            lines.append(f"  - chapter_name: {entry.title}")
            lines.append(f"  - chapter_number: {chapter_num}")
            lines.append(f"  - volume_name: {entry.volume_name}")
            lines.append(f"  - volume_number: {entry.volume_number}")
            lines.append(f"  - source: {entry.chapter_id}.html")
            lines.append(f"  - excluded: {'y' if entry.excluded else 'n'}")
            lines.append("")
            audit_rows.append((entry.title, filename, output_path.parent / filename))
            audit_toc_meta.append(AuditTocMeta(
                sequence_number=seq_num,
                chapter_number=chapter_num,
                volume_name=entry.volume_name,
                volume_number=entry.volume_number,
            ))

        lines.extend(build_audit_table_lines(
            audit_rows, strip_sml=strip_sml, toc_meta=audit_toc_meta,
        ))

        output_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("TextTocWriter: wrote %s (%d entries)", output_path, len(entries))


_TEXT_CHAPTER_HEADING_RE = re.compile(r"^## \[(.+?)\]\(ch_\d{4}\.\w+\)$")


class TextTocReader:
    def read(self, toc_path: Path) -> list:
        from syntrive.adapters.epub.merged_toc_writer import MergedTocEntry
        from syntrive.adapters.toc_audit import AUDIT_SECTION_HEADING

        if not toc_path.exists():
            logger.warning("TextTocReader: file not found: %s", toc_path)
            return []
        try:
            raw = toc_path.read_text(encoding="utf-8")
        except OSError as exc:
            logger.error("TextTocReader: cannot read %s: %s", toc_path, exc)
            return []

        def _build_entry(title: str, attrs: dict[str, str]) -> "MergedTocEntry":
            source = attrs.get("source", "").strip()
            chapter_id = source[:-5] if source.endswith(".html") else source
            if not chapter_id:
                logger.warning(
                    "TextTocReader: %s: entry %r has no/blank source field -- "
                    "chapter_id will be empty",
                    toc_path, title,
                )
            excl_raw = attrs.get("excluded", "n").strip().lower()
            return MergedTocEntry(
                chapter_id=chapter_id,
                title=attrs.get("chapter_name", "").strip() or title,
                source_files=[],
                excluded=(excl_raw == "y"),
                is_discard=False,
                volume_name=attrs.get("volume_name", "").strip(),
                volume_number=attrs.get("volume_number", "").strip(),
                chapter_number=(
                    attrs["chapter_number"].strip() if "chapter_number" in attrs else None
                ),
                sequence_number=attrs.get("sequence_number", "").strip(),
            )

        entries: list = []
        current_title: Optional[str] = None
        current_attrs: dict[str, str] = {}
        for line in raw.splitlines():
            stripped = line.strip()
            if stripped == AUDIT_SECTION_HEADING:
                break
            if not stripped or stripped.startswith("<!--") or stripped == "# TOC":
                continue
            m = _TEXT_CHAPTER_HEADING_RE.match(stripped)
            if m:
                if current_title is not None:
                    entries.append(_build_entry(current_title, current_attrs))
                current_title = m.group(1).replace("\\[", "[").replace("\\]", "]")
                current_attrs = {}
                continue
            if stripped.startswith("- ") and current_title is not None:
                am = re.match(r"^- (\w+):\s*(.*)$", stripped)
                if am:
                    current_attrs[am.group(1)] = am.group(2).strip()
        if current_title is not None:
            entries.append(_build_entry(current_title, current_attrs))

        logger.info("TextTocReader: parsed %s -- %d entries", toc_path.name, len(entries))
        return entries

